import localFont from "next/font/local";
import { Inter } from "next/font/google";  // Add Inter from Google Fonts
import "./globals.css";

// Load Inter from Google Fonts
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", // Use CSS variable for the font
  display: "swap",  // Ensures good loading behavior
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
